language: java
dist: trusty
jdk:
  - oraclejdk8
addons:
  chrome: stable
  firefox: "66.0.5"
before_install:
  - pwd
  - ls -la
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: true
  local-dir: build/reports/spec
  on:
    branch: master